### ISSUE TITLE
Adding some of the relevant posts I wrote

### ISSUE THREAD

**Issue by sohamkamani** [danistefanovic/build-your-own-x#1]
- **Main programming language**: Node.js
- **Tutorial title**: How to make a responsive telegram bot
- **Tutorial URL**: https://www.sohamkamani.com/blog/2016/09/21/making-a-telegram-bot/
- **Category**: Bot

- **Main programming language**: Go
- **Tutorial title**: Build a web application in Go
- **Tutorial URL**: https://www.sohamkamani.com/blog/2017/09/13/how-to-build-a-web-application-in-golang/
- **Category**: Web Server

**Comment by danistefanovic** [comment]
I've added both tutorials. Thanks! 

As soon as I have more tutorials, I will move "Build a web application in Go" from "Uncategorized" to a new category "Web Application"
