### ISSUE TITLE
A 3D Modeller

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#100]
### Main programming language
Python

### Tutorial title
A 3D Modeller

### Tutorial URL
http://aosabook.org/en/500L/a-3d-modeller.html

### Category
* [x] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by aneu13** [comment]
Nice!

**Comment by danistefanovic** [comment]
@theSyndical Thanks a lot!
