### ISSUE TITLE
Programming The Blockchain in C#

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#101]
### Main programming language
C#

### Tutorial title
Programming The Blockchain in C#

### Tutorial URL
https://programmingblockchain.gitbooks.io/programmingblockchain/

### Category
* [ ] 3D Renderer
* [x] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
🙌
