### ISSUE TITLE
3D Game Development with LWJGL 3

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#102]
### Main programming language
Java

### Tutorial title
3D Game Development with LWJGL 3

### Tutorial URL
https://lwjglgamedev.gitbooks.io/3d-game-development-with-lwjgl/content/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
