### ISSUE TITLE
(How to Write a (Lisp) Interpreter (in Python))

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#103]
### Main programming language
Python

### Tutorial title
(How to Write a (Lisp) Interpreter (in Python))

### Tutorial URL
http://norvig.com/lispy.html

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
🍻
