### ISSUE TITLE
Computer Graphics from scratch

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#104]
### Main programming language
Psudocode

### Tutorial title
Computer Graphics from scratch [WIP]

### Tutorial URL
http://www.gabrielgambetta.com/computer-graphics-from-scratch/introduction.html

### Category
* [x] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome resource, thanks a lot!
