### ISSUE TITLE
Write your own miniature Redis with Python

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#106]
### Main programming language
Python

### Tutorial title
Write your own miniature Redis with Python

### Tutorial URL
http://charlesleifer.com/blog/building-a-simple-redis-server-with-python/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot!
