### ISSUE TITLE
Making a  package in Elixir

### ISSUE THREAD

**Issue by faraazahmad** [danistefanovic/build-your-own-x#111]
### Main programming language
Elixir

### Tutorial title
Build an  Elixir package

### Tutorial URL
https://codeburst.io/writing-your-first-package-in-elixir-part-1-901a5de071a6

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot for your submission. Tutorials in this list should describe something more concrete and tangible (e.g. how to build a database from scratch) that is not too tied to a programming language.  But thanks anyway!
