### ISSUE TITLE
Build your own Android Movie finder App

### ISSUE THREAD

**Issue by Tobibur** [danistefanovic/build-your-own-x#112]
### Main programming language
Java

### Tutorial title

Android Movie Finder App: Tutorial

### Tutorial URL
https://tobiburblog.wordpress.com/2018/04/23/android-movie-finder-app-tutorial/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. Unfortunately, the article isn’t at the quality standard required to add it to the list (code is not properly indented, the project is too basic for an app). Thanks.
