### ISSUE TITLE
"mal" in "Programming languages"

### ISSUE THREAD

**Issue by vi** [danistefanovic/build-your-own-x#113]
### Main programming language

Lisp (with a lot of implementations already)

### Tutorial title

Make a Lisp

### Tutorial URL

https://github.com/kanaka/mal

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by theSyndical** [comment]
they're well documented but they don't walk you through the process.

**Comment by vi** [comment]
mal provides [an instruction](https://github.com/kanaka/mal/blob/master/process/guide.md), describing what should be done on each step, also providing testcases for each step.

> Mal is a learning tool. See the make-a-lisp process guide. Each implementation of mal is separated into 11 incremental, self-contained (and testable) steps that demonstrate core concepts of Lisp. The last step is capable of self-hosting (running the mal implementation of mal).

**Comment by danistefanovic** [comment]
I've added it to the list
* The main purpose of the "mal" repository is learning
* There is a [step-by-step guide](https://github.com/kanaka/mal/blob/master/process/guide.md#the-make-a-lisp-process-1)
* Many examples in different languages are available which can be compared to each other

Thanks @vi!
