### ISSUE TITLE
The Super Tiny Compiler, in Go

### ISSUE THREAD

**Issue by hazbo** [danistefanovic/build-your-own-x#114]
### Main programming language
Go

### Tutorial title
The Super Tiny Compiler

### Tutorial URL
https://github.com/hazbo/the-super-tiny-compiler

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot!
