### ISSUE TITLE
C++ Tetris Tutorial with SDL

### ISSUE THREAD

**Issue by cpusam** [danistefanovic/build-your-own-x#118]
### Main programming language

C++

### Tutorial title

Tetris Tutorial in C++ Platform Independent Focused in Game Logic for Begginers

### Tutorial URL
http://javilop.com/gamedev/tetris-tutorial-in-c-platform-independent-focused-in-game-logic-for-beginners/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [X] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks a lot!
