### ISSUE TITLE
C++ : Write Your Own Operating System

### ISSUE THREAD

**Issue by bauripalash** [danistefanovic/build-your-own-x#123]
### Main programming language
C++

### Tutorial title
Write Your Own Operating System

### Tutorial URL
http://www.youtube.com/playlist?list=PLHh55M_Kq4OApWScZyPl5HhgsTJS9MZ6M

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [✓] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome, thanks a lot!

**Comment by bauripalash** [comment]
I'm Happy to help
