### ISSUE TITLE
Add Programming Language/Pascal "Let's Build a Compiler, by Jack Crenshaw"

### ISSUE THREAD

**Issue by psema4** [danistefanovic/build-your-own-x#124]
### Main programming language
Pascal

### Tutorial title
Let's Build a Compiler, by Jack Crenshaw

### Tutorial URL
https://compilers.iecc.com/crenshaw/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by zfrisch** [comment]
Correct me if I'm wrong, isn't this the tutorial series that was never quite finished?

**Comment by danistefanovic** [comment]
Added, thanks!
