### ISSUE TITLE
Remove "Build a Twitter Bot in less than 30 minutes"

### ISSUE THREAD

**Issue by sushinoya** [danistefanovic/build-your-own-x#126]
I was very excited to have chanced upon this repo and I looked through some of the tutorials. Some were great while a few weren't. _Node.js: Why you should have your own Twitter Bot, and how to build one in less than 30 minutes_ was one of the latter kinds.

I might be mistaken but I thought that this repo should contain projects which enhance your understanding such that you can build something by yourself. In the process of building, one may use other libraries and refer to other projects.

But tutorials like the Twitter Bot one ask the users to clone a whole project pre-made by the author and then make tweaks here and there before deploying it. Don't get me wrong, the article is beautifully written and is very easy to follow but I just feel that it goes against the spirit of this repo about creating and understanding. When Feynman talked about understanding, I'm sure he didn't mean _understanding_ this way.

I apologise if I misunderstood the purpose of the repository. Either way, I am grateful to all the contributors for curating such a useful list of resources. Cheers :)

**Comment by danistefanovic** [comment]
Thanks a lot for your feedback. To use a pre-made project and just to tweak some settings is actually an exclusion criterion. I've somehow overlooked that in the mentioned tutorial – my mistake. I'll check all the tutorials in the next days.

Generally, it's not always easy for me to draw a line in the sand on what is considered as "built from scratch" (e.g., what kind of libraries are allowed?). I'm open to suggestions.

**Comment by sushinoya** [comment]
@danistefanovic Let me know if you need any help looking through them or assessing other PRs because I understand that there are quite a few :) Anyway, thanks for considering my complaint and thanks for maintaining this repo :)

**Comment by danistefanovic** [comment]
I went through all of the tutorials and removed those that rely too much on libraries and have not enough "own logic". Feel free to open a new issue if you find something that can be improved. Thanks again for your input!
