### ISSUE TITLE
tePLSQL a PL/SQL Template engine

### ISSUE THREAD

**Issue by osalvador** [danistefanovic/build-your-own-x#128]
### Main programming language
PL/SQL

### Tutorial title
PL/SQL Template engine

### Tutorial URL
https://github.com/osalvador/tePLSQL

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [x] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. Unfortunately, the submitted repository does not have the character of a tutorial. Tutorials in this list should provide a guided path for learners, either through a step-by-step article or by breaking down code into multiple digestible parts that are easy to follow (preferably with comments). But thanks anyway!
