### ISSUE TITLE
Build a static site generator with Node.JS

### ISSUE THREAD

**Issue by doug2k1** [danistefanovic/build-your-own-x#130]
### Main programming language
Node.js

### Tutorial title
Build a static site generator in 40 lines with Node.js

### Tutorial URL
https://medium.com/douglas-matoso-english/build-static-site-generator-nodejs-8969ebe34b22

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot!
