### ISSUE TITLE
LLVM Kaleidoscope Tutorial

### ISSUE THREAD

**Issue by ntchambers** [danistefanovic/build-your-own-x#131]
### Main programming language

C++

### Tutorial title

Kaleidoscope: Implementing a Language with LLVM

### Tutorial URL
https://llvm.org/docs/tutorial/LangImpl01.html

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
