### ISSUE TITLE
Understanding JavaScript Micro-Templating

### ISSUE THREAD

**Issue by zfrisch** [danistefanovic/build-your-own-x#132]
### Main programming language

JavaScript
### Tutorial title

Understanding JavaScript Micro Templating by Zak Frisch
### Tutorial URL
https://medium.com/wdstack/understanding-javascript-micro-templating-f37a37b3b40e
### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [x] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
