### ISSUE TITLE
[Enhancement Proposal] : Create a Github Page

### ISSUE THREAD

**Issue by bauripalash** [danistefanovic/build-your-own-x#136]
I think it would be a good idea to host this repo information  via `GitHub Page` rather than a single `Readme.md`, it would easy to find for novice people.

**Comment by amirouche** [comment]
It's good enough like that.

**Comment by bauripalash** [comment]
What about them who are new to Github but still want to build something of their own.

**Comment by unnamedd** [comment]
I like the idea, but create the page just because the novice people isn't reason enough to create it, iIMHO. GitHub isn't an alien land. If you make a simple research on Google using the correct term you will find not only the page as you will find this repo as well. 

So, novice people isn't a good reason, in my opinion.

**Comment by rvben** [comment]
Looking at other lists, like the famous '[awesome](https://github.com/sindresorhus/awesome)'-lists, it seems very common just to have it in a README.md file.

**Comment by bauripalash** [comment]
But I think a page will be more attractive than a README.md

**Comment by unnamedd** [comment]
@bauripalash will be nice but will be one more place to manage

**Comment by danistefanovic** [comment]
* As @rvben pointed out, it's very common to use the README for such curated lists
* All of these tutorials require some basic programming knowledge. Someone who can write some lines of code should also be able to open and scroll through this repo.
* Links have to be managed on two places if the current README is kept as it is
* Running a website also means to be compliant with various laws (hello GDPR)

Let's keep it simple for now.
