### ISSUE TITLE
gifbot - Building a GitHub App

### ISSUE THREAD

**Issue by ColinEberhardt** [danistefanovic/build-your-own-x#138]
### Main programming language
JavaScript

### Tutorial title
gifbot - Building a GitHub App

### Tutorial URL
http://blog.scottlogic.com/2017/05/22/gifbot-github-integration.html

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [x] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!

**Comment by ColinEberhardt** [comment]
Thanks @danistefanovic - and kudos for creating a list with proper curation, so many of the 'awesome' lists out there are far from awesome!

**Comment by danistefanovic** [comment]
Thanks a lot for the kind words!
