### ISSUE TITLE
Building a BitTorrent client from scratch in C#

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#139]
### Main programming language
C#

### Tutorial title
Building a BitTorrent client from scratch in C#

### Tutorial URL
https://www.seanjoflynn.com/research/bittorrent.html

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot!
