### ISSUE TITLE
Bittorrent client in Python 3.5

### ISSUE THREAD

**Issue by eliasson** [danistefanovic/build-your-own-x#141]
### Main programming language
Python

### Tutorial title
A BitTorrent client in Python 3.5

### Tutorial URL
http://markuseliasson.se/article/bittorrent-in-python/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Great work. Thanks!
