### ISSUE TITLE
Traffic sign classification using CNN

### ISSUE THREAD

**Issue by avidLearnerInProgress** [danistefanovic/build-your-own-x#143]
### Main programming language
Python

### Tutorial title
 Traffic signs classification with a CNN

### Tutorial URL
https://navoshta.com/traffic-signs-classification/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [x] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you!
