### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by mayursojitra** [danistefanovic/build-your-own-x#144]
### Main Programming Language
Android

### Tutorial Title
Starting Android Development with Android Studio

### Tutorial URL
https://www.theandroid-mania.com/starting-android-development-with-android-studio/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
There is no coding involved in this tutorial.
