### ISSUE TITLE
Android - Timeline ( Time Track ) With Recyclerview

### ISSUE THREAD

**Issue by mayursojitra** [danistefanovic/build-your-own-x#145]
### Main programming language
Android

### Tutorial title
Timeline ( Time Track ) With Recyclerview

### Tutorial URL
https://github.com/mayursojitra/Timeline-With-Recycler-View

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Not a tutorial
