### ISSUE TITLE
Driver drowsiness detection using python

### ISSUE THREAD

**Issue by avidLearnerInProgress** [danistefanovic/build-your-own-x#149]
### Main programming language
Python

### Tutorial title
Python: _Driver drowsiness detection using opencv and python_

### Tutorial URL
http://pythonopencv.com/driver-drowsiness-detection-using-opencv-and-python/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks a lot!
