### ISSUE TITLE
Learn Go with a Simple Server

### ISSUE THREAD

**Issue by hriddhidey** [danistefanovic/build-your-own-x#151]
### Main programming language
Golang

### Tutorial title
Learn Go with a Simple Server

### Tutorial URL
https://github.com/adnaan/learngo

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [x] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks for your submission. Unfortunately, it does not fit the purpose of this repo. The submitted tutorial is focused on explaining Go concepts rather than showing what's behind the scenes of a web server. Thanks anyway!

**Comment by hriddhidey** [comment]
No problems! Are you sure you actually went through the tutorial though? Because the entire tutorial is based on a TDD approach to building a web server. This helped me out a lot when I started out building web services in Go, so thought I'd share.

Nevertheless, apologies if this was a misfit. Huge fan of this repository though. Keep up the great work!
