### ISSUE TITLE
Stock Market Predictions with LSTM in Python

### ISSUE THREAD

**Issue by avidLearnerInProgress** [danistefanovic/build-your-own-x#155]
### Main programming language
Python

### Tutorial title
Python: _Stock Market Predictions with LSTM in Python_

### Tutorial URL
https://www.datacamp.com/community/tutorials/lstm-python-stock-market

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
🙌
