### ISSUE TITLE
Writing a Unix Shell - Part II

### ISSUE THREAD

**Issue by MarcNME** [danistefanovic/build-your-own-x#157]
### Main programming language
C

### Tutorial title
Writing a Unix Shell - Part II

### Tutorial URL
https://indradhanush.github.io/blog/writing-a-unix-shell-part-2/

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [X] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. If a tutorial consists of multiple parts, only the first one is added to this list. But thanks anyway!
