### ISSUE TITLE
Writing a Unix Shell - Part III

### ISSUE THREAD

**Issue by MarcNME** [danistefanovic/build-your-own-x#158]
### Main programming language
C

### Tutorial title

Writing a Unix Shell - Part III

### Tutorial URL
https://indradhanush.github.io/blog/writing-a-unix-shell-part-3/

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [X] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
See https://github.com/danistefanovic/build-your-own-x/issues/157#issuecomment-393292806
