### ISSUE TITLE
Build a simple OS for the raspberry pi

### ISSUE THREAD

**Issue by randombenj** [danistefanovic/build-your-own-x#160]
### Main programming language
Assembly

### Tutorial title
Baking Pi – Operating Systems Development

### Tutorial URL
http://www.cl.cam.ac.uk/projects/raspberrypi/tutorials/os/index.html

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [x] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
