### ISSUE TITLE
Kha Tutorial Series

### ISSUE THREAD

**Issue by lewislepton** [danistefanovic/build-your-own-x#162]
### Main programming language

Haxe

### Tutorial title

Kha Tutorial Series

### Tutorial URL
https://github.com/lewislepton/kha-tutorial-series
https://www.youtube.com/playlist?list=PL4neAtv21WOmmR5mKb7TQvEQHpMh1h0po

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [x] Front-end Framework / Library
* [X] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
The same as in https://github.com/danistefanovic/build-your-own-x/pull/47#issuecomment-388897932 (Although I like your presentation style). Sorry!
