### ISSUE TITLE
openFrameworks tutorial

### ISSUE THREAD

**Issue by lewislepton** [danistefanovic/build-your-own-x#163]
### Main programming language

C++

### Tutorial title

openFrameworks Tutorial

### Tutorial URL
https://www.youtube.com/playlist?list=PL4neAtv21WOmrV8z9rSzL20QpdLU1zJLr
https://github.com/lewislepton/openFrameworksTutorialSeries

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [X] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Great work, Lewis. Unfortunately, your series is not "project-based" and so it does not fit the purpose of this repo, sorry. Thanks anyway for your submission!
