### ISSUE TITLE
Let's Build A Simple Interpreter

### ISSUE THREAD

**Issue by peeyush-tm** [danistefanovic/build-your-own-x#164]
### Main programming language

Python
### Tutorial title

Let's Build A Simple Interpreter

### Tutorial URL
https://ruslanspivak.com/lsbasi-part1/

###  Code Repository
https://github.com/rspivak/lsbasi

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Awesome. Thank you!
