### ISSUE TITLE
MVC from scratch in PHP

### ISSUE THREAD

**Issue by Chaitya62** [danistefanovic/build-your-own-x#166]
### Main programming language
PHP

### Tutorial title
Write your own MVC from scratch in PHP

### Tutorial URL
https://chaitya62.github.io/2018/04/29/Writing-your-own-MVC-from-Scratch-in-PHP.html

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

Note: Sending a PR soon.

**Comment by keneo** [comment]
Are jokes allowed in comments? ;)

**Comment by Chaitya62** [comment]
@keneo  as long as they are funny... :p

**Comment by danistefanovic** [comment]
Added with #167. Thanks!
