### ISSUE TITLE
Build your own cache

### ISSUE THREAD

**Issue by kezhenxu94** [danistefanovic/build-your-own-x#169]
### Main programming language

Kotlin

### Tutorial title

**Build your own cache**

### Tutorial URL

http://kezhenxu94.me/2018/05/27/Build-Your-Own-Cache/

Or

https://github.com/kezhenxu94/cache-lite/blob/master/README.md

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

> "Cache", if you would add a category

**Comment by kezhenxu94** [comment]
@danisterfanovic what do you think? Should I open a pr? PING here if anything I did wrong

**Comment by danistefanovic** [comment]
Added. Thanks!
