### ISSUE TITLE
C# Wrapper over Firebase DB

### ISSUE THREAD

**Issue by AshV** [danistefanovic/build-your-own-x#170]
### Main programming language
C#

### Tutorial title
Creating C# Wrapper Over Firebase API For CRUD Operations

### Tutorial URL
https://www.ashishvishwakarma.com/creating-c-sharp-wrapper-over-firebase-api-for-basic-crud/
Repo URI : https://github.com/AshV/Firebase.Net

### Category
* [ ] 3D Renderer
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [X] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. Unfortunately, it does not fit the purpose of this repo. Tutorials in this list should explain more basic concepts (e.g. how a DB works behind the scenes). Creating a Firebase wrapper is a very specific topic around a particular service.

**Comment by AshV** [comment]
Ok, no problem.
 Do you think it can be placed in Uncategorized section?

**Comment by danistefanovic** [comment]
No, sorry. But thanks anyway for your submission!
