### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Gotham13121997** [danistefanovic/build-your-own-x#174]
### Main programming language

Python

### Tutorial title

Telegram Bot
### Tutorial URL
https://medium.com/@abhinavgautam/hackathon-bot-den-tea-party-and-making-telegram-bots-in-python-d0cc4aef76ae

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [X] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
There is almost no coding involved. Thanks anyway for your submission!
