### ISSUE TITLE
Nodejs Tutorial

### ISSUE THREAD

**Issue by ArnoutPullen** [danistefanovic/build-your-own-x#175]
### Main programming language
Nodejs

### Tutorial title
Build a RESTful API Using Node and Express 4

### Tutorial URL
https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks for your submission! To keep this list concise, I'm adding only tutorials that explain more basic concepts and contain some "own logic". Your submitted article is great but it's more about stitching different libraries together. Thanks anyway!
