### ISSUE TITLE
Reactjs

### ISSUE THREAD

**Issue by zerubeus** [danistefanovic/build-your-own-x#176]
### Main programming language
Javascript

### Tutorial title
React Internals

### Tutorial URL
http://www.mattgreer.org/articles/react-internals-part-one-basic-rendering/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ X] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome. Thanks a lot!
