### ISSUE TITLE
Write You a Scheme

### ISSUE THREAD

**Issue by rmnd551** [danistefanovic/build-your-own-x#177]
### Main programming language

Haskell

### Tutorial title

Write Yourself a Scheme in 48 Hours
Write You A Scheme, Version 2

### Tutorial URL
https://en.wikibooks.org/wiki/Write_Yourself_a_Scheme_in_48_Hours
https://github.com/write-you-a-scheme-v2/scheme

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [X] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot!
