### ISSUE TITLE
Build your own Serverless platform

### ISSUE THREAD

**Issue by johnpaulada** [danistefanovic/build-your-own-x#178]
### Main programming language
(any)

### Tutorial title
Uncovering the magic: How serverless platforms really work!

### Tutorial URL
https://medium.com/openwhisk/uncovering-the-magic-how-serverless-platforms-really-work-3cb127b05f71

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by CallbackFire** [comment]
iamn interested in the technology :)

**Comment by danistefanovic** [comment]
Thanks for your submission. Unfortunately, there is no coding involved in this tutorial.
