### ISSUE TITLE
Build a simple chatbot

### ISSUE THREAD

**Issue by HiddeVogelpoel** [danistefanovic/build-your-own-x#179]
### Main programming language
Elixir

### Tutorial title
Make your own ChatBot with Elixir

### Tutorial URL
[BotSquad](https://botsquad.com)

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [x] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks for your submission. Unfortunately, it's not a tutorial.
