### ISSUE TITLE
Learning operating system development using Linux kernel and Raspberry Pi

### ISSUE THREAD

**Issue by guptaanmol184** [danistefanovic/build-your-own-x#180]
### Main programming language
C

### Tutorial title
Learning operating system development using Linux kernel and Raspberry Pi

### Tutorial URL
https://github.com/s-matyukevich/raspberry-pi-os

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [x] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot!
