### ISSUE TITLE
Create a chatbot in Elixir

### ISSUE THREAD

**Issue by HiddeVogelpoel** [danistefanovic/build-your-own-x#181]
### Main programming language

Elixir

### Tutorial title

How to make a chatbot

### Tutorial URL
[Right here](https://github.com/HiddeVogelpoel/EasyChatBots/blob/master/README.md)

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [x ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by hkxicor** [comment]
Complete steps missing in the tutorial.

**Comment by HiddeVogelpoel** [comment]
The main tutorials are on the website itself.
You need to make a free account

**Comment by hkxicor** [comment]
As I know this repo only accepts something unique which enlightens the
black box behind the technology.

**Comment by Skydragonsz** [comment]
Not really a tutorial, on your github page you just link to the site that last time was closed (#179)

**Comment by danistefanovic** [comment]
Tutorials in this repo...
* ...should involve coding
* ...must contain "own logic" and shouldn't only demonstrate the usage of a library
* ...have to be free and shouldn't be hidden behind a login wall


@HiddeVogelpoel Thanks anyway for your submission!
