### ISSUE TITLE
Let's Build a Simple Database

### ISSUE THREAD

**Issue by peymanslh** [danistefanovic/build-your-own-x#186]
### Main programming language
C
### Tutorial title
**Let's Build a Simple Database**
Writing a sqlite clone from scratch in C

### Tutorial URL
https://cstack.github.io/db_tutorial/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
It's already on the list. But thanks anyway!
