### ISSUE TITLE
Write your own blockchain and PoW algorithm using Crystal!

### ISSUE THREAD

**Issue by bradford-hamilton** [danistefanovic/build-your-own-x#189]
### Main programming language

Crystal

### Tutorial title
Write your own blockchain and PoW algorithm using Crystal!

### Tutorial URL
https://medium.com/@bradford_hamilton/write-your-own-blockchain-and-pow-algorithm-using-crystal-d53d5d9d0c52

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [x] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by aichholzer** [comment]
Excellent!

**Comment by danistefanovic** [comment]
Great work! Added.
