### ISSUE TITLE
Build a news chatbot using Next.js and Dialogflow

### ISSUE THREAD

**Issue by avidLearnerInProgress** [danistefanovic/build-your-own-x#191]
### Main programming language
JavaScript

### Tutorial title
Build a news chatbot using Next.js and Dialogflow

### Tutorial URL
https://pusher.com/tutorials/news-chatbot-nextjs-dialogflow

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [x] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Same as #185. But thanks anyway for your submission!
