### ISSUE TITLE
Implement your own — call(), apply() and bind() method in JavaScript

### ISSUE THREAD

**Issue by ankur-anand** [danistefanovic/build-your-own-x#196]
### Main programming language

JavaScript

### Tutorial title

Implement your own — call(), apply() and bind() method in JavaScript

### Tutorial URL
https://medium.com/@ankur_anand/implement-your-own-call-apply-and-bind-method-in-javascript-42cc85dba1b

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Hey Ankur, thanks for your submission! The article contains some grammatical mistakes. It should be possible to fix them with tools like [Grammarly](https://www.grammarly.com). Let me know when you've updated your Medium post.

**Comment by ankur-anand** [comment]
Hi Daniel, Thanks for the feedback, I've updated the post. Please let me know if you still find mistakes, English is not a native language of mine, so I might have missed certain more grammatical rule.

**Comment by danistefanovic** [comment]
Added. Thanks!

Found a typo: "MDN" should always be written in uppercase.
