### ISSUE TITLE
Merge "Search Engine" and "Web Search Engine"

### ISSUE THREAD

**Issue by flynn16** [danistefanovic/build-your-own-x#198]
The "Search Engine" category and the "Web Search Engine" category have the same topic, so I suggest you merge them into one category.

**Comment by danistefanovic** [comment]
The "Web Search Engine" category is about how to create a system to search for information on the internet (e.g. like Google, Bing, Yahoo). "Search Engine" on the other hand, focuses on the search engine storage and indexing.
