### ISSUE TITLE
Writing Your Own Toy Compiler Using Flex, Bison and LLVM

### ISSUE THREAD

**Issue by ffesseler** [danistefanovic/build-your-own-x#2]
- **Main programming language**: Flex, Bison and LLVM
- **Tutorial title**: Writing Your Own Toy Compiler Using Flex
- **Tutorial URL**: https://gnuu.org/2009/09/18/writing-your-own-toy-compiler/
- **Category**: compiler

**Comment by danistefanovic** [comment]
Thanks!
