### ISSUE TITLE
Build-a-Linux

### ISSUE THREAD

**Issue by dospunk** [danistefanovic/build-your-own-x#200]
### Main programming language
any

### Tutorial title
Build Your Own Linux Distro

### Tutorial URL
https://github.com/danistefanovic/build-your-own-x/issues/new

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [x ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Invalid URL

**Comment by dospunk** [comment]
Pasted the wrong one, fixed it now

**Comment by danistefanovic** [comment]
Thanks! Unfortunately, it's more about configuring than coding, so it does not fit the purpose of this repo. Something similar was already submitted: https://github.com/danistefanovic/build-your-own-x/issues/34. But thanks anyway!

**Comment by dospunk** [comment]
Fair enough, have a nice day!
