### ISSUE TITLE
Scheme-coin

### ISSUE THREAD

**Issue by bor0** [danistefanovic/build-your-own-x#201]
### Main programming language
Scheme

### Tutorial title
Example cryptocurrency implementation in Scheme

### Tutorial URL
https://github.com/bor0/scheme-coin

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [x] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. Unfortunately, the provided link is not a tutorial in the strict sense.
