### ISSUE TITLE
Question:  What category should 'aws lambda' be categorized.

### ISSUE THREAD

**Issue by metrue** [danistefanovic/build-your-own-x#202]
### Main programming language
Golang

### Tutorial title
Build your own aws lambda

### Tutorial URL
https://github.com/metrue/fx

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. Unfortunately, it's not a tutorial.
