### ISSUE TITLE
Writing a shell in C

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#203]
### Main programming language

C 
### Tutorial title

Writing a shell in C
### Tutorial URL
https://prakashdanish.github.io/2018/01/15/write-a-shell.html
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [x] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Great, thank you!
