### ISSUE TITLE
Tutorial - Write a System Call (Linux)

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#204]
### Main programming language

C
### Tutorial title

Tutorial - Write a System Call
### Tutorial URL
https://brennan.io/2016/11/14/kernel-dev-ep3/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
