### ISSUE TITLE
Reimplementing Tetris in C and ncurses

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#205]
### Main programming language

C
### Tutorial title

On Tetris and Reimplementation
### Tutorial URL
https://brennan.io/2015/06/12/tetris-reimplementation/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks 🙌
