### ISSUE TITLE
Space Invaders from Scratch

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#206]
### Main programming language

C++
### Tutorial title

Space Invaders from Scratch - Part 1
### Tutorial URL
http://nicktasios.nl/posts/space-invaders-from-scratch-part-1.html
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

P.S. This tutorial has 3 more parts, with each having a link to the next part.

**Comment by danistefanovic** [comment]
Added. Thanks! 🙌
