### ISSUE TITLE
Make your own blog (in pure PHP)

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#207]
### Main programming language

PHP
### Tutorial title

Make your own blog
### Tutorial URL
https://ilovephp.jondh.me.uk/en/tutorial/make-your-own-blog
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Great one. Thanks!
