### ISSUE TITLE
Building a spell-checker with Clojure

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#208]
### Main programming language

Clojure
### Tutorial title

Clojure hands-on tutorial for beginners: building a spell-checker
### Tutorial URL
https://bernhardwenzel.com/articles/clojure-spellchecker/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
