### ISSUE TITLE
Implementing a virtual machine in C

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#209]
### Main programming language

C
### Tutorial title

Implementing a virtual machine in C
### Tutorial URL
https://felixangell.com/blog/implementing-a-virtual-machine-in-c/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Nice. Thanks!
