### ISSUE TITLE
Build your own error-correction fountain code with Luby Transform Codes

### ISSUE THREAD

**Issue by Spriteware** [danistefanovic/build-your-own-x#212]
### Main programming language
Python

### Tutorial title
Introduction to fountain codes: LT Codes with Python

### Tutorial URL
https://franpapers.com/en/algorithmic/2018-introduction-to-fountain-codes-lt-codes-with-python/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ x] Uncategorized

### Suggested title
Build your own error-correction fountain code with Luby Transform Codes

**Comment by omeid** [comment]
I think this would be fit okay with _Neural Network/AI_.

**Comment by Spriteware** [comment]
Not really, there is no _intelligence_ in it, there are only a few statistics and probability calculus. 

Due to the field of application, it is more related to _Network Stack_ since it is a way to correct errors of data transfers over lossy networks. But it is neither a tutorial to build a _stack_.

**Comment by danistefanovic** [comment]
Great article. Thanks a lot!
