### ISSUE TITLE
Contribution - Build your own Shopify App with Node.js and Express

### ISSUE THREAD

**Issue by LizCouto** [danistefanovic/build-your-own-x#213]
### Main programming language
Node.js 

### Tutorial title

Building a Shopify application with Node.js and Express

### Tutorial URL
https://help.shopify.com/api/tutorials/building-node-app

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [X ] Uncategorized

**Comment by omeid** [comment]
I don't think this is a good fit for this list. Build an integration is hardly building your own x.

**Comment by danistefanovic** [comment]
I'm the same opinion as @omeid. But thanks anyway for your submission!
