### ISSUE TITLE
Remaking Cavestory in C++

### ISSUE THREAD

**Issue by runderwo** [danistefanovic/build-your-own-x#216]
### Main programming language

C++

### Tutorial title

Remaking Cavestory in C++

### Tutorial URL
https://www.youtube.com/watch?v=ETvApbD5xRo

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [X] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks a lot!
