### ISSUE TITLE
Writing a git stats analysis tool using Go

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#218]
### Main programming language

Go
### Tutorial title

Visualize your local git contributions with Go: Tutorial on Writing a Git stats analysis cli tool using Go
### Tutorial URL
https://flaviocopes.com/go-git-contributions/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

P.S. I put this under Uncategorized instead of under Git, as this isn't about git itself, but about a utility to look at git contributions.

**Comment by danistefanovic** [comment]
Thanks!
