### ISSUE TITLE
Build the cowsay command with Go

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#220]
### Main programming language

Go
### Tutorial title

Building a cli command with Go: cowsay
### Tutorial URL
https://flaviocopes.com/go-tutorial-cowsay/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
