### ISSUE TITLE
Rewriting the cat command from scratch [video]

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#223]
### Main programming language

C
### Tutorial title

cat
### Tutorial URL
https://learnto.computer/screencasts/bsd-cat
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
