### ISSUE TITLE
Let's Make a Voxel Engine

### ISSUE THREAD

**Issue by rby90** [danistefanovic/build-your-own-x#224]
### Main programming language
C++

### Tutorial title
Let's Make a Voxel Engine

### Tutorial URL
https://sites.google.com/site/letsmakeavoxelengine/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome. Thanks!
