### ISSUE TITLE
Build your Own Search Engine for your Blog/Page with Javascript

### ISSUE THREAD

**Issue by shreybs** [danistefanovic/build-your-own-x#225]
JavaScript

Build Your own Custom Search Engine using JavaScript

https://blog.imaginea.com/build-your-own-custom-search-engine-using-javascript/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [. ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. Unfortunately, it's too basic to fit into this category. The tutorial is more focused on the UI part rather than the search index. But thanks anyway!
