### ISSUE TITLE
Simple AI Chatbot With Web Speech API And Node.js

### ISSUE THREAD

**Issue by midhmanohar** [danistefanovic/build-your-own-x#227]
### Main programming language
Node.js

### Tutorial title
Building A Simple AI Chatbot With Web Speech API And Node.js

### Tutorial URL
https://www.smashingmagazine.com/2017/08/ai-chatbot-web-speech-api-node-js/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [x] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
