### ISSUE TITLE
Building Neural Networks in F# — Part 1 & Part 2

### ISSUE THREAD

**Issue by hsed** [danistefanovic/build-your-own-x#228]
### Main programming language
F#

### Tutorial title
Building Neural Networks in F# — Part 1
Building Neural Networks in F# — Part 2

### Tutorial URL
Part 1 -- https://towardsdatascience.com/building-neural-networks-in-f-part-1-a2832ae972e6
Part 2 -- https://towardsdatascience.com/building-neural-networks-in-f-part-2-training-evaluation-5e3a68889da6

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [x] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Great work! Added.

**Comment by hsed** [comment]
Thanks! 👍😊

**Comment by hsed** [comment]
PS: Although this is a minor thing but there seems to be an extra space near the closing "_" for the article's title in README.md.
