### ISSUE TITLE
How to Build An Artificial Neural Network in Java

### ISSUE THREAD

**Issue by eldanieldev** [danistefanovic/build-your-own-x#229]
### Main programming language
Java

### Tutorial title
How to Build An Artificial Neural Network in Java

### Tutorial URL
https://www.linkedin.com/pulse/how-build-artificial-neural-network-java-rahul-raj/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ X] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks for posting! Unfortunately, it's more a tutorial on how to use DL4J rather than "building" something from scratch. Thanks anyway!
