### ISSUE TITLE
Let’s implement a cryptocurrency in Kotlin

### ISSUE THREAD

**Issue by VasilyFomin** [danistefanovic/build-your-own-x#230]
### Main programming language
Kotlin

### Tutorial title
Let’s implement a cryptocurrency in Kotlin

### Tutorial URL
https://medium.com/@vasilyf/lets-implement-a-cryptocurrency-in-kotlin-part-1-blockchain-8704069f8580

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [x] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome! I'm eager to see the next parts of your series. Thanks for submitting!
