### ISSUE TITLE
Writing a simple shell in Go

### ISSUE THREAD

**Issue by sj14** [danistefanovic/build-your-own-x#231]
### Main programming language

Go

### Tutorial title

Writing a simple shell in Go

### Tutorial URL
https://sj14.gitlab.io/post/2018-07-01-go-unix-shell/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [X] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Great work. Thanks for submitting!
