### ISSUE TITLE
How to build Snake using only JavaScript, HTML & CSS

### ISSUE THREAD

**Issue by humarh-dharnarh** [danistefanovic/build-your-own-x#232]
### Main programming language
Javascript

### Tutorial title
[Link to tutorial](https://medium.freecodecamp.org/think-like-a-programmer-how-to-build-snake-using-only-javascript-html-and-css-7b1479c3339e)

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [X] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by bauripalash** [comment]
Tutorial Title is : **Think like a programmer: How to build Snake using only JavaScript, HTML & CSS**

**Comment by danistefanovic** [comment]
Added. Thanks!
