### ISSUE TITLE
Learn Redux – Introduction To State Management With React

### ISSUE THREAD

**Issue by farhadmpr** [danistefanovic/build-your-own-x#233]
### Main programming language
Javascript

### Tutorial title
Learn Redux – Introduction To State Management With React

### Tutorial URL
https://codingthesmartway.com/learn-redux-introduction-to-state-management-with-react/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [x] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by bauripalash** [comment]
I can't understand , what we are actually **building** ?
It's just a tutorial

**Comment by danistefanovic** [comment]
I am of the same opinion as @bauripalash.

@farhadmpr Thanks anyway for your submission!
