### ISSUE TITLE
Writing a Game Boy emulator, Cinoop

### ISSUE THREAD

**Issue by sbmthakur** [danistefanovic/build-your-own-x#235]
### Main programming language
C

### Tutorial title
Writing a Game Boy emulator, Cinoop

### Tutorial URL
https://cturt.github.io/cinoop.html
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [x] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks a lot! 👌
