### ISSUE TITLE
Learn how React Reconciler package works by building your own lightweight React DOM

### ISSUE THREAD

**Issue by prometheansacrifice** [danistefanovic/build-your-own-x#236]
### Main programming language
Javascript

### Tutorial title
Learn how React Reconciler package works by building your own lightweight React DOM

### Tutorial URL
https://medium.com/@prometheansacrifice/learn-you-some-custom-react-renderers-aed7164a4199

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [x] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
