### ISSUE TITLE
Building a Simple URL Shortener With Just HTML and Javascript

### ISSUE THREAD

**Issue by bauripalash** [danistefanovic/build-your-own-x#237]
### Main programming language

JavaScript

### Tutorial title

Building a Simple URL Shortener With Just HTML and Javascript

### Tutorial URL
https://palash.tk/Build-URL-Shortener-With-HTML-JS

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by bauripalash** [comment]
It's My First Article about building something!

**Comment by danistefanovic** [comment]
Thanks, Palash! There are some grammatical errors in your article. You can use services like [Grammarly](https://grammarly.com) to fix them (it's free)

**Comment by bauripalash** [comment]
@danistefanovic Thanks For Suggestion, I'll surely try it now!

**Comment by bauripalash** [comment]
@danistefanovic , Check Again I tried fixing mistakes with help of Grammarly

**Comment by danistefanovic** [comment]
Added! Thanks.
