### ISSUE TITLE
Evolutionary Tetris AI using JS

### ISSUE THREAD

**Issue by IsaacWatt** [danistefanovic/build-your-own-x#240]
### Main programming language
JavaScript

### Tutorial title
How to make an Evolutionary Tetris AI

### Tutorial URL
https://www.youtube.com/watch?v=xLHCMMGuN0Q

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [x] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
