### ISSUE TITLE
python search engine

### ISSUE THREAD

**Issue by perrot** [danistefanovic/build-your-own-x#241]
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [v ] Search Engine
[Create Your Own Search Engine with Python](http://www.zackgrossbart.com/hackito/search-engine-python/)
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks for the submission. Unfortunately, the tutorial is too basic to fit into this category. Tutorials in "search engine" should cover more profound topics such as indexing and parsing.
