### ISSUE TITLE
Building a LISP from scratch with Swift

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#242]
### Main programming language

Swift
### Tutorial title

Building a LISP from scratch with Swift
### Tutorial URL
https://www.uraimo.com/2017/02/05/building-a-lisp-from-scratch-with-swift/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks a lot. Your submissions are always great!
