### ISSUE TITLE
Little Lisp: A small Lisp interpreter in Javascript

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#244]
### Main programming language

Javascript
### Tutorial title

Little Lisp interpreter
### Tutorial URL
https://maryrosecook.com/blog/post/little-lisp-interpreter
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks! 🍻
