### ISSUE TITLE
JSON Decoding Algorithm (JSON Parser)

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#246]
### Main programming language
Python

### Tutorial title
JSON Decoding Algorithm

### Tutorial URL
https://github.com/cheery/json-algorithm

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by tjysdsg** [comment]
Support!

**Comment by danistefanovic** [comment]
Added. Thanks!

**Comment by tjysdsg** [comment]
Thx!
