### ISSUE TITLE
Loading and rendering 3D skeletal animations from scratch in C# and GLSL

### ISSUE THREAD

**Issue by theSyndical** [danistefanovic/build-your-own-x#252]
### Main programming language
C#

### Tutorial title
Loading and rendering 3D skeletal animations from scratch in C# and GLSL

### Tutorial URL
https://www.seanjoflynn.com/research/skeletal-animation.html

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
