### ISSUE TITLE
Build a tiny package manager.

### ISSUE THREAD

**Issue by g-plane** [danistefanovic/build-your-own-x#254]
### Main programming language
TypeScript

### Tutorial title
Build a tiny package manager.

### Tutorial URL
https://github.com/g-plane/tiny-package-manager

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by NetOperatorWibby** [comment]
This is really neat!

**Comment by danistefanovic** [comment]
Added. Thanks!
