### ISSUE TITLE
Add PL tutorial

### ISSUE THREAD

**Issue by tekknolagi** [danistefanovic/build-your-own-x#255]
### Main programming language
OCaml

### Tutorial title
Writing a Lisp, the series

### Tutorial URL
https://bernsteinbear.com/blog/lisp/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
