### ISSUE TITLE
Building a simple Snake game on Ruby

### ISSUE THREAD

**Issue by AKovtunov** [danistefanovic/build-your-own-x#259]
### Main programming language
Ruby

### Tutorial title
Ruby Snake

### Tutorial URL
https://www.diatomenterprises.com/gamedev-on-ruby-why-not/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
