### ISSUE TITLE
Use subheadings instead of bullet points for the titles

### ISSUE THREAD

**Issue by adtac** [danistefanovic/build-your-own-x#26]
Subheadings can be permalinked (with `https://github.com/danistefanovic/build-your-own-x#location`). If I wanted to link the programming languages section, I can't right now.

Example:

```
#### Programming Languages

 - Foo
 - Bar
 - Baz
```

#### Programming Languages

 - Foo
 - Bar
 - Baz

You can't see the permalinks here, but they'll appear when used in the README.

**Comment by danistefanovic** [comment]
That's a good point 👍

Switched to subheadings with 1b64257b33b59867ba3eddd801eac5d333ad1cd8
