### ISSUE TITLE
c/c++ build a simple b+tree RDMS

### ISSUE THREAD

**Issue by enpeizhao** [danistefanovic/build-your-own-x#261]
### Main programming language

c/c++

### Tutorial title

c/c++ build a simple b+tree RDMS
### Tutorial URL
https://github.com/enpeizhao/duck_db

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [✓] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
English only, please
