### ISSUE TITLE
Build a bot to play poker

### ISSUE THREAD

**Issue by francescopeloi** [danistefanovic/build-your-own-x#262]
### Main programming language

Java

### Tutorial title

Build a bot to play poker

### Tutorial URL
https://github.com/pokerwars/pokerwars.io-starterbot-java

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [x] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [x] Web Server
* [ ] Uncategorized

**Comment by dropbeardan** [comment]
Is the URL restricted by any chance, getting 404's

**Comment by danistefanovic** [comment]
Link is not working

**Comment by francescopeloi** [comment]
It has been taken down overnight, I am asking why.
