### ISSUE TITLE
Build a bot to play poker

### ISSUE THREAD

**Issue by francescopeloi** [danistefanovic/build-your-own-x#263]
### Main programming language

Java

### Tutorial title

Build a bot to play poker

### Tutorial URL
https://github.com/pokerwars/pokerwars.io-starterbot-java

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [x] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [x] Web Server
* [ ] Uncategorized

The repository was mistakenly flagged by github, it's fine now.

**Comment by danistefanovic** [comment]
Thanks for the re-submission. Unfortunately, it does not fit in this repo. Tutorials in this list should provide a guided path for learners, either through a step-by-step article or by breaking down code into multiple digestible parts that are easy to follow (preferably with comments). But thanks anyway!

**Comment by francescopeloi** [comment]
Thanks for your review @danistefanovic ! 

In the github repo readme we link to documentation on how to build the bot (https://www.pokerwars.io/docs/) and the main classes have comments to explain what the bot is doing (e.g. https://github.com/pokerwars/pokerwars.io-starterbot-java/blob/master/src/main/java/io/pokerwars/bot/PokerwarsController.java and https://github.com/pokerwars/pokerwars.io-starterbot-java/blob/master/src/main/java/io/pokerwars/bot/strategies/RandomPokerStrategy.java).
Also we have a service to run a bot quickly (https://www.pokerwars.io/bot) which then links to the code used to build it, would this documentation not be enough?

Anyway the aim of pokerwars is to help learners to get into programming and AI. Maybe we are not very user friendly at the moment, but we aim to get there. It's just a side project so it might get a while :) If we are not enough just now, I'll try to open again when we have improved the experience.

Thanks again!
