### ISSUE TITLE
Add api tutorial

### ISSUE THREAD

**Issue by enzobarrett** [danistefanovic/build-your-own-x#267]
### Main programming language

Python
### Tutorial title

Implementing a RESTful Web API with Python & Flask
### Tutorial URL
http://blog.luisrei.com/articles/flaskrest.html
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [x] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added with #275
