### ISSUE TITLE
Nim tutorial links in uncategorized don't work

### ISSUE THREAD

**Issue by JaanJah** [danistefanovic/build-your-own-x#269]
### Main programming language

Nim

### Tutorial title

Nim: Writing a DMIDecode Parser
Nim: Writing a INI Parser
Nim: Writing a Link Checker
Nim: Writing a URL Shortening Service

### Tutorial URL
https://xmonader.github.io/nimdays/day1_dmidecode.html#cid1
https://xmonader.github.io/nimdays/day5_iniparser.html#cid13
https://xmonader.github.io/nimdays/day4_asynclinkschecker.html#cid10
https://xmonader.github.io/nimdays/day7_shorturl.html#cid20

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Fixed with PR #264. Thanks!
