### ISSUE TITLE
Rust: Writing Scalable Chat Service from Scratch

### ISSUE THREAD

**Issue by leowzukw** [danistefanovic/build-your-own-x#286]
### Main programming language

Rust

### Tutorial title

Rust in Detail: Writing Scalable Chat Service from Scratch

### Tutorial URL

https://nbaksalyar.github.io/2015/07/10/writing-chat-in-rust.html

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [X] Uncategorized

A [second part](https://nbaksalyar.github.io/2015/07/10/writing-chat-in-rust.html) follows. Even though the author uses some library, he is digging in low level stuff and is not just gluing library together.

**Comment by danistefanovic** [comment]
Thanks!
