### ISSUE TITLE
How to build a simple actor-based blockchain

### ISSUE THREAD

**Issue by elleFlorio** [danistefanovic/build-your-own-x#288]
### Main programming language
Scala

### Tutorial title
How to build a simple actor-based blockchain

### Tutorial URL
https://medium.freecodecamp.org/how-to-build-a-simple-actor-based-blockchain-aac1e996c177

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [x] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Great work!
