### ISSUE TITLE
Add `Build Your Own Shell using Rust`

### ISSUE THREAD

**Issue by JoshMcguigan** [danistefanovic/build-your-own-x#289]
### Main programming language
Rust

### Tutorial title
Build Your Own Shell using Rust

### Tutorial URL
https://www.joshmcguigan.com/blog/build-your-own-shell-rust/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [x] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks, Josh!
