### ISSUE TITLE
Please Remove "C++: How To Make Minecraft in C++/ OpenGL"

### ISSUE THREAD

**Issue by Hopson97** [danistefanovic/build-your-own-x#290]
Hi! 

I am the creator of the "C++: How To Make Minecraft in C++/ OpenGL " series, but I do not support this series anymore for several reasons, and it is very unfinished/ cut off early before anything interesting actually happens. 

I appreciate it was added to this list, but would like it removed so people will stop finding the videos and complaining to me when they realize that the tutorials are pretty bad (hence I do not support it) and the fact it is is unfinished.

Proof I am the creator: https://github.com/Hopson97/Minecraft-Tutorial 

Thanks! :)

**Comment by rat** [comment]
This is so sad. I studied a lot through videos

**Comment by danistefanovic** [comment]
Removed
