### ISSUE TITLE
Add `Build Your Own Web Browser using Python`

### ISSUE THREAD

**Issue by temberature** [danistefanovic/build-your-own-x#291]
### Main programming language
Python

### Tutorial title
Building a Web Browser

### Tutorial URL
https://in.udacity.com/course/programming-languages--cs262
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
No tutorials that require you to create an account. Sorry!
