### ISSUE TITLE
Add "Demystifying compilers by writing your own"

### ISSUE THREAD

**Issue by macabeus** [danistefanovic/build-your-own-x#292]
### Main programming language
Elixir

### Tutorial title
Demystifying compilers by writing your own

### Tutorial URL
Talk: https://www.youtube.com/watch?v=zMJYoYwOCd4
Repository with the source code and more informations: https://github.com/macabeus/macro-compiler 

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
