### ISSUE TITLE
Build your own clipboard manager

### ISSUE THREAD

**Issue by prashantgupta24** [danistefanovic/build-your-own-x#295]
### Main programming language
Python

### Tutorial title
How to create your own clipboard manager using python and Tkinter

### Tutorial URL

https://medium.com/@prashantgupta24/how-to-create-your-own-clipboard-manager-using-python-and-tkinter-e693aa27fffc

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by prashantgupta24** [comment]
Whoops. My bad. I had added it to the PR but forgot in the issue. Added it now.

**Comment by danistefanovic** [comment]
Hey Prashant, thanks a lot for your submission! Unfortunately, I don't think your tutorial fits in this repo because it lacks a little depth. All the heavy lifting is done by `pyperclip`. But thanks anyway!

**Comment by prashantgupta24** [comment]
Would it help if I used Tkinter's built in clipboard handler functions? All pyperclip does is copy from and paste to the clipboard. Tkinter has that functionality built in, I can replace pyperclip with that.

Also I can add the second part of the tutorial which adds more functionality to the application. 

Let me know if either one of the steps can help make my application fulfil the requirements.
