### ISSUE TITLE
Build Your Own Service Mesh Framework

### ISSUE THREAD

**Issue by cesarvr** [danistefanovic/build-your-own-x#296]
### Main programming language
Javascript/Node.js

### Tutorial title
Creating Your Own Istio

### Tutorial URL
https://cesarvr.io/post/istio/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

Service Mesh Maybe?

**Comment by danistefanovic** [comment]
Hey Cesar. Great post series! 👏Unfortunately, it's more of an installation/configuration guide than a programming tutorial. I'm closing this in order to keep the list concise and focused on programming topics. Thanks anyway for your submission!
