### ISSUE TITLE
Write your Own Virtual Machine

### ISSUE THREAD

**Issue by sbmthakur** [danistefanovic/build-your-own-x#299]
### Main programming language
C

### Tutorial title
Write your Own Virtual Machine

### Tutorial URL
https://justinmeiners.github.io/lc3-vm/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by giacomoguiulfo** [comment]
Since there is another link on virtual machines (although it needs to be fixed, see #300), there could potentially be a new category: `Virtual Machine`.

**Comment by xsnk** [comment]
Perhaps, the VM and Emulator category can be combined.

**Comment by danistefanovic** [comment]
Thanks!
