### ISSUE TITLE
Build your own Web Application

### ISSUE THREAD

**Issue by naclcaleb** [danistefanovic/build-your-own-x#303]
### Main programming languages
HTML, CSS, JS, PHP, Python

### Tutorial title
Building Web Applications from Scratch

### Tutorial URL
https://github.com/naclcaleb/Webcourse

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ x] Uncategorized

This tutorial is a work-in-progress repository of teaching lessons on building web applications using the regular web languages: HTML, CSS, JS and backend languages like PHP and Python.

**Comment by danistefanovic** [comment]
Unfortunately, there is no code in your tutorial, and so it does not fit the purpose of this repo.

**Comment by naclcaleb** [comment]
Yea, I knew it was a long shot, but I thought I might as well try. It will have code eventually, but still won't exactly be a succinct tutorial.
