### ISSUE TITLE
The first link in "Build your own Visual Recognition System" doesn't work.

### ISSUE THREAD

**Issue by abhy-kumar** [danistefanovic/build-your-own-x#307]
### Main programming language
Python

### Tutorial title
Build your own Visual Recognition System

### Tutorial URL
https://github.com/danistefanovic/build-your-own-x#build-your-own-visual-recognition-system

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [x] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by jackwilsdon** [comment]
It looks like it's still available on [The Wayback Machine](https://web.archive.org/web/20180118083557/http://pythonopencv.com:80/driver-drowsiness-detection-using-opencv-and-python), however all of the image assets appear to be missing.

**Comment by danistefanovic** [comment]
Thanks for pointing that out!
