### ISSUE TITLE
building a standalone module in javascript with only node file system

### ISSUE THREAD

**Issue by souparno** [danistefanovic/build-your-own-x#308]
### Main programming language

javascript
### Tutorial title

building a standalone module in javascript with only node file system
### Tutorial URL
https://github.com/souparno/js-io
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [* ] Uncategorized

**Comment by souparno** [comment]
no, but its something, written in the minimal line of code, that i find, very useful to lean how nodejs serves its modules.

**Comment by danistefanovic** [comment]
@souparno Thank you for the submission! As @jackwilsdon pointed out, it's unfortunately not a tutorial.
