### ISSUE TITLE
Front-end Framework / Library Tutorial (React)

### ISSUE THREAD

**Issue by fmonteiro** [danistefanovic/build-your-own-x#31]
- **Main programming language (max. 1)**: JavaScript
- **Tutorial title**: Gooact: React in 160 lines of JavaScript
- **Tutorial URL**: https://medium.com/@sweetpalma/gooact-react-in-160-lines-of-javascript-44e0742ad60f
- **Category**: Front-end Framework / Library

**Comment by danistefanovic** [comment]
Great article. Thanks!
