### ISSUE TITLE
Flexible Rasterizer in OpenCL

### ISSUE THREAD

**Issue by git-knight** [danistefanovic/build-your-own-x#312]
### Main programming language
OpenCL (C/C++)

### Tutorial title
Flexible Rasterizer in OpenCL

### Tutorial URL
https://github.com/a2flo/oclraster/tree/master/

### Category
* [x] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by jackwilsdon** [comment]
Is there a tutorial element to this? I believe most of the things found in this repository are primarily tutorials.

**Comment by git-knight** [comment]
i put this tutorial mostly only for the rasterizer.cl part because i didn't know before how to optimize rasterizers for GPU without hitting the GPU bandwidth bottleneck, the c++ part is not much interest and is only for demo, so it was supposed to be like "how to optimize a rasterizer for GPU" tutorial

**Comment by git-knight** [comment]
can u make it a sub-tutorial for those who wants to know how to port a rasterizer on GPU ?

**Comment by git-knight** [comment]
i have no idea why but when i pressed ctrl+enter for sending a message i got "(me) closed the issue"
