### ISSUE TITLE
Writing http-server using event-loops.

### ISSUE THREAD

**Issue by flouthoc** [danistefanovic/build-your-own-x#314]
This project focuses on teaching concept of event-loops [EPOLL] and using it to write HTTP server

### Main programming language
C

### Tutorial title
Thread-less, event-loop based http-server from scratch using epoll. Learning Purpose. 

### Tutorial URL
https://github.com/flouthoc/envelop.c/

### Category
* [ ] Web Server

**Comment by flouthoc** [comment]
@danistefanovic Could you please take a look

**Comment by danistefanovic** [comment]
Thanks for your submission! Code repos in this list should contain either a detailed README and/or a very well-documented code. Both are insufficient. Sorry!
