### ISSUE TITLE
Rust and OpenGL from scratch

### ISSUE THREAD

**Issue by Julien-Broyard** [danistefanovic/build-your-own-x#316]
### Main programming language
Rust

### Tutorial title
Rust and OpenGL from scratch

### Tutorial URL
http://nercury.github.io/rust/opengl/tutorial/2018/02/08/opengl-in-rust-from-scratch-00-setup.html

### Category
* [x] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks for your submission! Unfortunately, I don't think this tutorial fits the purpose of this repo as it's not building something from scratch. It's more a how-to on how to use OpenGL in Rust. Thanks anyway!
