### ISSUE TITLE
Adventures in Rust: A Basic 2D Game

### ISSUE THREAD

**Issue by Julien-Broyard** [danistefanovic/build-your-own-x#322]
### Main programming language
Rust

### Tutorial title
Adventures in Rust: A Basic 2D Game

### Tutorial URL
https://a5huynh.github.io/2018/02/02/adventures-in-rust.html

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Added. Thanks!
