### ISSUE TITLE
Roguelike Tutorial in Rust + tcod

### ISSUE THREAD

**Issue by Julien-Broyard** [danistefanovic/build-your-own-x#323]
### Main programming language
Rust

### Tutorial title
Roguelike Tutorial in Rust + tcod

### Tutorial URL
https://tomassedovic.github.io/roguelike-tutorial/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thanks!
