### ISSUE TITLE
Write yourself a Git

### ISSUE THREAD

**Issue by Emmsii** [danistefanovic/build-your-own-x#339]
_Not my own tutorial, thought it would be a good fit here._

### Main programming language
Python

### Tutorial title
Write yourself a Git!

### Tutorial URL
https://wyag.thb.lt/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [X] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
👉 https://github.com/danistefanovic/build-your-own-x/pull/340
