### ISSUE TITLE
Node.js: Build a static site generator in 40 lines with Node.js. 

### ISSUE THREAD

**Issue by Alex7437** [danistefanovic/build-your-own-x#350]
It's a dead link!

**Comment by Alex7437** [comment]
@danistefanovic

**Comment by v00** [comment]
https://www.webdevdrops.com/build-static-site-generator-nodejs-8969ebe34b22/

Is it that article?

**Comment by Alex7437** [comment]
Yeah, but when I tried it the other day it gave me a 404 error - oh well!

**Comment by char16t** [comment]
Please reopen issue. I sent PR to update broken link
