### ISSUE TITLE
Added "Writing a Blockchain in Node.js" (JavaScript)

### ISSUE THREAD

**Issue by micheleriva** [danistefanovic/build-your-own-x#378]
### Main programming language
JavaScript

### Tutorial title
Writing a Blockchain in Node.js

### Tutorial URL
https://www.jsmonday.dev/articles/34/writing-a-blockchain-in-node-js

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [x] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by chinedu360** [comment]
love the tutorial...its very explanatory.

**Comment by p-g-krish** [comment]
i like it

**Comment by danistefanovic** [comment]
👌
