### ISSUE TITLE
Writing a simple VPN in Go 

### ISSUE THREAD

**Issue by manigandand** [danistefanovic/build-your-own-x#382]
### Main programming language
Go

### Tutorial title
**pin** a simple tunnel client and server which is configured to act as a VPN.

### Tutorial URL
https://github.com/aki237/pin

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [x] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Not a tutorial. Thanks anyway!
