### ISSUE TITLE
An Introduction to Convolutional Neural Networks

### ISSUE THREAD

**Issue by vzhou842** [danistefanovic/build-your-own-x#396]
### Main programming language
Python

### Tutorial title
An Introduction to Convolutional Neural Networks

### Tutorial URL
https://victorzhou.com/blog/intro-to-cnns-part-1/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [x] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by philippstangl** [comment]
Awesome tutorial! Great work!
I added it to my repo: 
https://github.com/philippstangl/whatever/blob/master/computer-science.md#artificial-intelligence

**Comment by danistefanovic** [comment]
Great work @vzhou842  🙌
