### ISSUE TITLE
Another game?

### ISSUE THREAD

**Issue by kylebakerio** [danistefanovic/build-your-own-x#40]
- **Main programming language (max. 1)**: Javascript
- **Tutorial title**: Developing Games with React, Redux, and SVG - Part 1
- **Tutorial URL**: https://auth0.com/blog/developing-games-with-react-redux-and-svg-part-1/
- **Category**: game

Note: this is actually from your own tweet: https://twitter.com/DaniStefanovic/status/961586529763291136

**Comment by danistefanovic** [comment]
I knew I knew it from somewhere. Thank you for your submission!
