### ISSUE TITLE
Build your own Load Balancer

### ISSUE THREAD

**Issue by jonaylor89** [danistefanovic/build-your-own-x#409]
### Main programming language
Golang

### Tutorial title
Let's Create a Simple Load Balancer

### Tutorial URL
https://kasvith.github.io/posts/lets-create-a-simple-lb-go/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ x] Uncategorized

**Comment by danistefanovic** [comment]
🙌
