### ISSUE TITLE
submission: Bitwise

### ISSUE THREAD

**Issue by lunaticLipid** [danistefanovic/build-your-own-x#41]
- **Main programming language (max. 1)**:  C
- **Tutorial title**: Building a software and hardware stack for a simple computer from scratch.
- **Tutorial URL**: https://www.youtube.com/watch?v=ZjwvMcP3Nf0&list=PLU94OURih-CiP4WxKSMt3UcwMSDM3aTtX
- **Category**: Uncategorized

**Comment by danistefanovic** [comment]
Great, thanks a lot!
