### ISSUE TITLE
Building a BitTorrent client from the ground up in Go

### ISSUE THREAD

**Issue by nisanio** [danistefanovic/build-your-own-x#423]
### Main programming language

Go
### Tutorial title

Building a BitTorrent client from the ground up in Go
### Tutorial URL
https://blog.jse.li/posts/torrent/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ X] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by abowassm** [comment]
بناء عميل تورنت من الألف إلى الياء في Go

**Comment by abowassm** [comment]
Cryptocurrency

**Comment by danistefanovic** [comment]
duplicate
