### ISSUE TITLE
building a blockchain with Javascript video tutorial

### ISSUE THREAD

**Issue by AlexFloresVeliz** [danistefanovic/build-your-own-x#44]
- **Main programming language (max. 1)**: Javascript
- **Tutorial title**: Building a blockchain with Javascript
- **Tutorial URL**: https://www.youtube.com/watch?v=zVqczFZr124&list=PLzvRQMJ9HDiTqZmbtFisdXFxul5k0F-Q4
- **Category**: Build your own `Blockchain / Cryptocurrency`

**Comment by danistefanovic** [comment]
Thanks! 🙌
