### ISSUE TITLE
I've been getting spam email from this thread

### ISSUE THREAD

**Issue by MarkoVlaic** [danistefanovic/build-your-own-x#444]
I got several emails with spam content from this repo (shown in the image). What is the appropriate way to react? 
![Screenshot_20200228-074957_Gmail](https://user-images.githubusercontent.com/10403655/75517430-f2e6d200-59fe-11ea-84c8-55bba13edcf4.jpg)

**Comment by WAUthethird** [comment]
Been seeing these too. Best thing to do is to delete the issues and report the accounts.

**Comment by danistefanovic** [comment]
Huh? I didn't get a notification for that. If you notice something like that again, please report the users.

**Comment by rawsGit** [comment]
I got several notifications too. I deleted most of them, but I was able to retrieve username and issue# from all but two of the notifications. 
helen78989 - #443
nelly567 - #437
Not exactly sure how to go about reporting the users, though.

**Comment by minecrawler** [comment]
you can report them on their profile page. Did that for yet another account and the GitHub team is working on it.

Who let the bots out?
