### ISSUE TITLE
Build a HTTP Server from Scratch in C

### ISSUE THREAD

**Issue by jo-fr** [danistefanovic/build-your-own-x#447]
### Main programming language

C

### Tutorial title

HTTP Server: Everything you need to know to Build a simple HTTP server from scratch

### Tutorial URL
https://medium.com/from-the-scratch/http-server-what-do-you-need-to-know-to-build-a-simple-http-server-from-scratch-d1ef8945e4fa

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [X] Web Server
* [ ] Uncategorized

**Comment by UbaidRussell** [comment]
Nice.

**Comment by UbaidRussell** [comment]
This is exactly what I needed

**Comment by mgamal92** [comment]
Great Article!

**Comment by SMUsamaShah** [comment]
Its behind paywall

**Comment by jo-fr** [comment]
@SMUsamaShah Oh yeah I didn’t notice. It should be possible to read within the 5 free articles you get from medium per month.
