### ISSUE TITLE
Bit torrent client using Go

### ISSUE THREAD

**Issue by gdhameeja** [danistefanovic/build-your-own-x#465]
### Main programming language

Go
### Tutorial title

Building a BitTorrent client from the ground up in Go
### Tutorial URL
https://blog.jse.li/posts/torrent/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ x ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by shirshak55** [comment]
i wish there was something for rust

**Comment by danistefanovic** [comment]
duplicate
