### ISSUE TITLE
Cordova: Facebook login tutorial

### ISSUE THREAD

**Issue by thekingrenz23** [danistefanovic/build-your-own-x#469]
### Main programming language
javascript

### Tutorial title
Cordova Tutorials: Facebook Login Part1: Setting up the plugin

### Tutorial URL
https://medium.com/@renzcarloasalanga/cordova-tutorials-facebook-login-part1-setting-up-the-plugin-d47f7390d1be?source=friends_link&sk=8efe23a6611aac44282953ffd2b614e9

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ /] Uncategorized

**Comment by danistefanovic** [comment]
This tutorial does not fit the purpose of this repository. Sorry!
