### ISSUE TITLE
Aggregation Framework For Web Data Using Javascript

### ISSUE THREAD

**Issue by Bladefidz** [danistefanovic/build-your-own-x#49]
- **Javascript**:
- **Aggregation Framework For Web Data**:
- **https://github.com/Bladefidz/web-aggregation/blob/master/README.md**:
- **data-mining, aggregation-frameowork**:

**Comment by danistefanovic** [comment]
Not a tutorial. But thanks anyway for your submission!

**Comment by Bladefidz** [comment]
Yes, you are right, it definitely not straight forward tutorial. It is just toy framework anyway. Two reasons why I submit that is it is help me to understand data pre-processing concept in the hard way and also being able to understand industry standard aggregation framework such as MongoDB.
