### ISSUE TITLE
ID3 Algorithm From Scratch

### ISSUE THREAD

**Issue by Bladefidz** [danistefanovic/build-your-own-x#50]
- **Python**:
- **An Introduction to Decision Tree Learning: ID3 Algorithm**:
- **https://medium.com/machine-learning-guy/an-introduction-to-decision-tree-learning-id3-algorithm-54c74eb2ad55**:
- **machine-learning**:

**Comment by danistefanovic** [comment]
The article contains many grammatical mistakes (checkout out [Grammarly](https://www.grammarly.com/), it's free) Tutorials in this list also should describe somehting more concrete and tangible like "Build your own *database*, *os*, *game*...*.

**Comment by Bladefidz** [comment]
Thank you for the feedback Dani. I will try to fix any grammatical errors later.
