### ISSUE TITLE
Broken link (rewrite cat command)

### ISSUE THREAD

**Issue by CaddyDz** [danistefanovic/build-your-own-x#502]
### Main programming language
C

### Tutorial title
C: Rewriting the cat command from scratch 

### [Tutorial URL](https://learnto.computer/screencasts/bsd-cat)

The heroku app seems to be down

> Application error
> An error occurred in the application and your page could not be served.

### Category
* [x] Command-Line Tool

**Comment by danistefanovic** [comment]
Fixed. Thanks!

https://github.com/danistefanovic/build-your-own-x/commit/d22c5e9f5ffd11d24542bd1f14295529b9710e52
