### ISSUE TITLE
One broken link

### ISSUE THREAD

**Issue by allergictoeng** [danistefanovic/build-your-own-x#523]
Video about CLI, is broken (C: Rewriting the cat command from scratch)
* [x] https://learnto.computer/screencasts/bsd-cat

**Comment by aaryanporwal** [comment]
I have the video downloaded, I can host it and send a PR of it.

**Comment by danistefanovic** [comment]
Thanks!

**Comment by aaryanporwal** [comment]
Rather than removing the link altogether use web archived link:
http://web.archive.org/web/20200414231251/https://learnto.computer/screencasts/bsd-cat
