### ISSUE TITLE
CLI rust tutorial :)

### ISSUE THREAD

**Issue by ergpopler** [danistefanovic/build-your-own-x#547]
### Main programming language

Rust
### Tutorial title

CLI tutorial -- Pikasay

### Tutorial URL
https://ergpopler.github.io/Tutorials/cli.html

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by Padrition** [comment]
The link is not working.
