### ISSUE TITLE
Broken Link for "Build your own Web Search Engine"

### ISSUE THREAD

**Issue by SkuzzyxD** [danistefanovic/build-your-own-x#556]
### Main programming language
Ruby

### Tutorial title
Build your own Web Search Engine

### Tutorial URL
https://blog.saush.com/2009/03/17/write-an-internet-search-engine-with-200-lines-of-ruby-code/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [x] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by gscho** [comment]
Would be cool if these articles were archived

**Comment by SkuzzyxD** [comment]
They would've been in wayback machine.

**Comment by danistefanovic** [comment]
Removed, thanks!
