### ISSUE TITLE
 Why you should build you own NoSQL Database

### ISSUE THREAD

**Issue by marceloboeira** [danistefanovic/build-your-own-x#56]
- **Main programming language (max. 1)**: Crystal
- **Tutorial title**: Why you should build you own NoSQL Database
- **Tutorial URL**: https://medium.com/@marceloboeira/why-you-should-build-your-own-nosql-database-9bbba42039f5
- **Category**: Database

**Comment by danistefanovic** [comment]
Thanks!

**Comment by marceloboeira** [comment]
No, thank you!
