### ISSUE TITLE
[Rust] So You Want to Build a Language VM

### ISSUE THREAD

**Issue by megahomyak** [danistefanovic/build-your-own-x#561]
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [X] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danielchim** [comment]
I think it fits better under Programming Language field, since believe the blog post focuses on making a language VM instead of emulating/virtualizing an operating system or a hardware.

**Comment by megahomyak** [comment]
But I think it will be much more intuitive (=> easy to find) if blog about making a VM will be in a section about VMs

**Comment by danielchim** [comment]
Fair point.
