### ISSUE TITLE
Broken link of "JavaScript: Build GIT - Learn GIT"

### ISSUE THREAD

**Issue by hadyelzayady** [danistefanovic/build-your-own-x#562]
I believe the new link should be this one https://kushagra.dev/blog/build-git-learn-git/

**Comment by genesis-algorithms** [comment]
I can verify it's broken as @hadyelzayady says

**Comment by danistefanovic** [comment]
Fixed with 458936621ea6231db568420016f88ea8196aa2aa. Thanks!
