### ISSUE TITLE
NES Emulator From Scratch in C++

### ISSUE THREAD

**Issue by rajivnayanc** [danistefanovic/build-your-own-x#564]
### Main programming language
C++

### Tutorial title
NES Emulator From Scratch

### Tutorial URL
https://www.youtube.com/playlist?list=PLrOv9FMX8xJHqMvSGB_9G9nZZ_4IgteYf 

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [X] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by EduardoJM** [comment]
This is added in the Pull Request https://github.com/danistefanovic/build-your-own-x/pull/489. See here: https://github.com/danistefanovic/build-your-own-x#build-your-own-emulator--virtual-machine

**Comment by rajivnayanc** [comment]
Okay. Will close this issue.
