### ISSUE TITLE
Nim Days tutorials

### ISSUE THREAD

**Issue by xmonader** [danistefanovic/build-your-own-x#57]
Hi I'm the author of Nim days book:  day by day projects from scratch not sure if it fits but it has writing bencode parser, ini parser, dmidecode parser, shorturl service, links checker and developing a `stow` like tool from scratch
 
- **Main programming language (max. 1)**: nim
- **Tutorial title**: Nim days 
- **Tutorial URL**: https://xmonader.github.io/nimdays/index.html
- **Category**:

**Comment by danistefanovic** [comment]
Thank you for your submission. Would you mind making a PR with a separate link to each of those tutorials?

**Comment by xmonader** [comment]
Sure thing Thanks :)
