### ISSUE TITLE
Python: The Complete Roguelike Tutorial [video] - broken link

### ISSUE THREAD

**Issue by DemianS** [danistefanovic/build-your-own-x#580]
Link to playlist is broken or not exist?

### Main programming language
Python

### Tutorial title
Python: The Complete Roguelike Tutorial [video]

### Tutorial URL
[**Python**: The Complete Roguelike Tutorial](https://www.youtube.com/playlist?list=PLKUel_nHsTQ1yX7tQxR_SQRdcOFyXfNAb)

### Category
* [ ] Game

**Tutorial is not exist anymore?**
Maybe [this is the right link now](https://www.youtube.com/watch?v=r47iWInWJp4&list=PL43PN07AM4J9N2eiVn43s9h7uJgbZH9Gp) ?

**Comment by danistefanovic** [comment]
Fixed with 5f548a4f4c517e11e43fc5a50e5813cc3fba608a. Thanks!
