### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by Mennaruuk** [danistefanovic/build-your-own-x#583]
## Broken links:
[**Python: Simple Iterator-based Parsing**](http://effbot.org/zone/simple-iterator-parser.htm) ([Wayback Machine](https://web.archive.org/web/20201106170443/http://effbot.org/zone/simple-iterator-parser.htm))
[**Python: Simple Top-Down Parsing in Python**](http://effbot.org/zone/simple-top-down-parsing.htm) ([Wayback Machine](https://web.archive.org/web/20201108113604/http://effbot.org/zone/simple-top-down-parsing.htm))
[**Go: Building Blockchain in Go**](https://jeiwan.cc/posts/building-blockchain-in-go-part-1/) ([new link](https://jeiwan.net/posts/building-blockchain-in-go-part-1/))
[**C#: How to create a Dragon in Augmented Reality in Unity ARCore [video]**](https://fr-film.net/v-how-to-create-a-dragon-in-augmented-reality-in-unity-arcore-tutorial-qTSDPkPyPqs.html) ([YouTube backup?](https://www.youtube.com/watch?v=qTSDPkPyPqs))
[**JavaScript: Build your own basic physics engine in JavaScript**](https://www.graphitedigital.com/blog/build-your-own-basic-physics-engine-in-javascript) ([Wayback Machine](https://web.archive.org/web/20201124145208/https://www.graphitedigital.com/blog/build-your-own-basic-physics-engine-in-javascript))
[**Ruby: A Unix Shell in Ruby**](https://www.jstorimer.com/blogs/workingwithcode/7766107-a-unix-shell-in-ruby) ([Wayback Machine](https://web.archive.org/web/20201112015401/https://www.jstorimer.com/blogs/workingwithcode/7766107-a-unix-shell-in-ruby))
[**Node.js: Build a static site generator in 40 lines with Node.js**](https://www.webdevdrops.com/build-static-site-generator-nodejs-8969ebe34b22) ([new site](https://www.webdevdrops.com/en/build-static-site-generator-nodejs-8969ebe34b22/))
[**C: Let's Build a Simple Database**](https://cstack.github.io/) ([new link?](https://cstack.github.io/db_tutorial/))

Thanks for maintaining this great list!

**Comment by agentfreedom** [comment]
Thank you too! It's good work!

вт, 2 февр. 2021 г., 20:32 Mennaruuk <notifications@github.com>:

**Comment by Mennaruuk** [comment]
Appreciate it :)

**Comment by DesmondWillowbrook** [comment]
[JavaScript: Build GIT - Learn GIT](https://kushagragour.in/blog/2014/01/build-git-learn-git/)
Broken link

**Comment by danistefanovic** [comment]
Fixed. Thanks!
