### ISSUE TITLE
Go: p2p messenger with end-to-end encryption

### ISSUE THREAD

**Issue by easmith** [danistefanovic/build-your-own-x#619]
### Main programming language
Go

### Tutorial title
p2p messenger with end-to-end encryption

### Tutorial URL
https://habr.com/ru/post/437686/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [X] Uncategorized

**Comment by danistefanovic** [comment]
English tutorials only. Thanks!
