### ISSUE TITLE
Add tutorial for Build your own C compiler with Python and LLVM

### ISSUE THREAD

**Issue by Mithrilwoodrat** [danistefanovic/build-your-own-x#629]
### Main programming language
Python

### Tutorial title
Building a C compiler with LLVM

### Tutorial URL
https://github.com/Mithrilwoodrat/naivecompiler

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [*] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by PedroCisnerosSantana** [comment]
You should provide a link to a tutorial

**Comment by Mithrilwoodrat** [comment]
> 

tutorial link: [Build your own C compiler with Python and LLVM 1](https://mithrilwoodrat.github.io/2019/02/16/%E7%BC%96%E8%AF%91%E5%99%A8%E5%BC%80%E5%8F%91%E4%BB%8E%E9%9B%B6%E5%8D%95%E6%8E%92%281%29/)

it's writen in chinese

**Comment by PedroCisnerosSantana** [comment]
I think it's best to add tutorials in English, so everyone can understand it better, but it's @danistefanovic choice

**Comment by Mithrilwoodrat** [comment]
> I think it's best to add tutorials in English, so everyone can understand it better, but it's @danistefanovic choice

Got It, I will add English tutorials when I have time
