### ISSUE TITLE
Nex Tutorial: Writing a sqlite clone from scratch in C

### ISSUE THREAD

**Issue by guptaanmol184** [danistefanovic/build-your-own-x#640]
### Main programming language
C

### Tutorial title
Writing a sqlite clone from scratch in C

### Tutorial URL
https://cstack.github.io/db_tutorial/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [x] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by fake-rookie** [comment]
This tutorial was already in list.
