### ISSUE TITLE
 Creating a Cryptocurrency Trading Bot with Python - Binance Exchange (Fixed)

### ISSUE THREAD

**Issue by Roibal** [danistefanovic/build-your-own-x#66]
### Main programming language

python
### Tutorial title

Creating a Cryptocurrency Trading Bot with Python - Binance Exchange
### Tutorial URL
https://www.youtube.com/playlist?list=PLIFBTFgFpoJ-2Qq6GFW-knNyAR9PcOwPw

### Category
* [ ] 3D Renderer
* [x ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
thanks!
