### ISSUE TITLE
Text Editor Tutorial: Build Your Own Text Editor

### ISSUE THREAD

**Issue by 4tydev** [danistefanovic/build-your-own-x#660]
### Main programming language

C
### Tutorial title

Build Your Own Text Editor
### Tutorial URL
https://viewsourcecode.org/snaptoken/kilo/index.html
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by fake-rookie** [comment]
already has this tutorial.

**Comment by 4tydev** [comment]
You're right, didn't notice at first, thank u!
