### ISSUE TITLE
Build your own npm package

### ISSUE THREAD

**Issue by the-unfactoring-guru** [danistefanovic/build-your-own-x#669]
### Main programming language

Javascript

### Tutorial title

Developing and Publishing an NPM Package

### Tutorial URL
https://auth0.com/blog/developing-npm-packages/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by 4tydev** [comment]
20 days waiting for approval

**Comment by the-unfactoring-guru** [comment]
I'm sorry i'm not waiting a long time like most of these people. I can wtite an article about this. Sorry
