### ISSUE TITLE
Creating Reddit Bot (Advanced) - Youtube Series - With Multiple Code Examples on Github

### ISSUE THREAD

**Issue by Roibal** [danistefanovic/build-your-own-x#67]
### Main programming language

python
### Tutorial title

Creating Reddit Bot (Advanced) - Youtube Series - With Code on Github
### Tutorial URL

https://www.youtube.com/playlist?list=PLIFBTFgFpoJ9vmYYlfxRFV6U_XhG-4fpP

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ x ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Great, thank you!
