### ISSUE TITLE
I made a C# networking tutorial series about a year+ ago

### ISSUE THREAD

**Issue by define-private-public** [danistefanovic/build-your-own-x#68]
I made this tutorial series because I was a little frustrated with the existing tutorials about how to use the networking APIs in C#/.NET.  It has a slew of sample projects: TCP chater server, TCP (text based) games, a Pong clone (realtime game server), etc.

Do you want to link to the whole series?  Or want me to pull out some individual section?

### Main programming language
C#

### Tutorial title
C# Networking Tutorial Series

### Tutorial URL
https://16bpp.net/tutorials/csharp-networking/preface

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [x] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by danistefanovic** [comment]
Great work!
