### ISSUE TITLE
Create a Bot with C# and Bot Builder SDK for .NET

### ISSUE THREAD

**Issue by frankodoom** [danistefanovic/build-your-own-x#69]
### Main programming language
c#

### Tutorial title
Create a bot with the Bot Builder SDK for .NET
### Tutorial URL
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-quickstart?view=azure-bot-service-3.0
### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
- [x] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Thank you for your submission. I’m afraid I’m going to have to pass. The outcome of this tutorial is a very basic "Hello world" bot and I don't think it fits the purpose of the repo. There are also many people in the comments that are struggling with this tutorial. But thanks anyway!
