### ISSUE TITLE
Implementing a Promises/A+ spec compliant JavaScript promise library from scratch (TDD way)

### ISSUE THREAD

**Issue by mauriciopoppe** [danistefanovic/build-your-own-x#75]
### Main programming language

JavaScript

### Tutorial title

Implementing a Promises/A+ spec compliant JavaScript promise library from scratch (TDD way)

### Tutorial URL

https://www.mauriciopoppe.com/notes/computer-science/computation/promises/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Server
* [X] Uncategorized

**Comment by danistefanovic** [comment]
Great work, thank you!
