### ISSUE TITLE
maybe add physics engine.

### ISSUE THREAD

**Issue by rhulha** [danistefanovic/build-your-own-x#79]

**Comment by rhulha** [comment]
Sure, here is my collection of links, I have not yet tried them out myself.

https://gafferongames.com/tags/physics/ (in reverse order)
http://buildnewgames.com/gamephysics/
http://buildnewgames.com/broad-phase-collision-detection/
https://mattmakesgames.tumblr.com/post/127890619821/towerfall-physics
http://www-cs-students.stanford.edu/~eparker/files/PhysicsEngine/
http://www.toptal.com/game/video-game-physics-part-ii-collision-detection-for-solid-objects
https://caseymuratori.com/blog_0003
https://sourceforge.net/projects/hacd/

**Comment by danistefanovic** [comment]
Thanks a lot! I've included the links where programming is involved.
