### ISSUE TITLE
Bitwise: Build your own software/hardware stack 

### ISSUE THREAD

**Issue by AB1908** [danistefanovic/build-your-own-x#83]
* **Main programming language**: C

* **Tutorial title**: Bitwise is an educational project where we create the software/hardware stack for a computer from scratch.

* **Tutorial URL**: https://github.com/pervognsen/bitwise

* **Category**: Emulator

**Comment by AB1908** [comment]
I found this "project" rather intimidating, considering the amount of stuff being touched upon, but it is definitely a worthwhile learning experience.

**Comment by g-berthiaume** [comment]
@AB1908 
Already in the `Uncategorized` section under the name `C: Building a software and hardware stack for a simple computer from scratch [video]` .

**Comment by danistefanovic** [comment]
@AB1908 Thank you for your submission! As @g-berthiaume pointed out, it's already on the list. Cheers!

**Comment by AB1908** [comment]
Aye my bad. I did a Ctrl+F and didn't find Bitwise.

**Comment by AB1908** [comment]
Also, it's not exactly a simple computer. Per aims to implement modern features so long as they have a good tradeoff for performance vs complexity.
