### ISSUE TITLE
Making games in Python

### ISSUE THREAD

**Issue by afro-nolan** [danistefanovic/build-your-own-x#84]
### Main programming language

Python

### Tutorial title

Making Games with Python & Pygame

### Tutorial URL
https://inventwithpython.com/makinggames.pdf

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome, thank you!
