### ISSUE TITLE
The very basics of a terminal emulator (writing a basic terminal emulator)

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#85]
### Main programming language

C
### Tutorial title

The very basics of a terminal emulator
### Tutorial URL
https://www.uninformativ.de/blog/postings/2018-02-24/0/POSTING-en.html
### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

P.S. I put it in Uncategorized since afaik a terminal emulator (e.g. gnome-terminal) isn't a shell (e.g. bash), but is rather a program used to host the shell.

**Comment by danistefanovic** [comment]
Thanks a lot! 👍

**Comment by Boltzmachine** [comment]
I run
```
./eduterm
```

but got 
```
Nothing to read from child: Input/output error
```

**Comment by sweetbbak** [comment]
its doesn't work. Try looking at Havoc (for a wayland implementation) or St (suckless term, for an X11 implementation)

**Comment by vain** [comment]
I cannot reproduce this issue. But FWIW, I added an “Errata” section at the end of the blog post, which might contain fixes: https://www.uninformativ.de/blog/postings/2018-02-24/0/POSTING-en.html#errata

Feel free to ping me if you find more mistakes. I only discovered this GitHub issue by accident.
