### ISSUE TITLE
8-ball pool game in 1 hour

### ISSUE THREAD

**Issue by kylebakerio** [danistefanovic/build-your-own-x#86]
### Main programming language

javascript

### Tutorial title
8-ball pool game with javascript and html in 1 hour

### Tutorial URL
https://www.youtube.com/watch?v=aXwCrtAo4Wc

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ x ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome, thanks a lot!
