### ISSUE TITLE
Add Zapier to Bot section

### ISSUE THREAD

**Issue by grahamplace** [danistefanovic/build-your-own-x#88]
Thanks @connorjacobsen for the idea to add!

### Main programming language
SQL

### Tutorial title
How to Build Your Own Slack Bot

### Tutorial URL
https://zapier.com/blog/how-to-build-chat-bot/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [x] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
It's a great and easy-to-follow article. Unfortunately, there is no coding involved and, thus, it doesn't fit the purpose of the repo, sorry. Thanks anyway for your submission!
