### ISSUE TITLE
Add tutorial

### ISSUE THREAD

**Issue by MarcNME** [danistefanovic/build-your-own-x#91]
### Main programming language
C

### Tutorial title
Kernel 201 - Let’s write a Kernel with keyboard and screen support

### Tutorial URL
https://arjunsreedharan.org/post/99370248137/kernel-201-lets-write-a-kernel-with-keyboard

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [x] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by danistefanovic** [comment]
Awesome, thank you!
