### ISSUE TITLE
Creating a simple todo application with Ruby on Rails

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#94]
### Main programming language

Ruby
### Tutorial title

Creating a simple ToDo application with Ruby on Rails - Part 1
### Tutorial URL
https://iridakos.com/tutorials/2013/12/07/creating-a-simple-todo-part-1
### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

P.S. This tutorial has 3 more parts, the next part being linked in the end of the previous one. I also put this in Uncategorized, as afaik there isn't a category for general applications that aren't games or emulators.

**Comment by danistefanovic** [comment]
Thanks for your submission! I'm not sure if it fits this repository. To-do apps became the new "hello world" programs and there are tons of tutorials about them out there. I'm trying to keep this list as concise and useful as possible with tutorials that cover underlying concepts or more sophisticated app examples. I'm afraid this list would explode if such tutorials would be added. Let me think about it.

**Comment by lmintmate** [comment]
Ah, I wasn't aware of this trend at all. This tutorial here and the other one from the same site I submitted (which is also a todo app, but a gtk linux one, so a more unusual implementation overall) are the first I've seen that propose the construction of a todo app, since I don't usually explicitly search for such tutorials but rather randomly encounter this genre sometimes while browsing. So no problem with me - it is your call to make after all.

**Comment by danistefanovic** [comment]
I'll close this for now. But thanks anyway!
