### ISSUE TITLE
Creating a Linux Desktop application with Ruby

### ISSUE THREAD

**Issue by lmintmate** [danistefanovic/build-your-own-x#95]
### Main programming language

Ruby
### Tutorial title

Creating a Linux Desktop application with Ruby
### Tutorial URL
https://iridakos.com/tutorials/2018/01/25/creating-a-gtk-todo-application-with-ruby
### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

P.S. I submit this in Uncategorized as there isn't afaik a category for general applications, that aren't games or emulators, on the list.

**Comment by danistefanovic** [comment]
Thanks!
