### ISSUE TITLE
Build your own Apollo Engine

### ISSUE THREAD

**Issue by mpicard** [danistefanovic/build-your-own-x#96]
### Main programming language
TypeScript

### Tutorial title
Make your own GraphQL metrics dashboard 

### Tutorial URL
http://all-loops-considered.org/2018/05/09/graphql-metrics-part-1/

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by mpicard** [comment]
It’s a combination of an http proxy, an API with a Postgres database and a react UI so I have no clue what category to put it in

**Comment by danistefanovic** [comment]
Great work! Thanks for the submission.

Note: There is a broken link in your article. I've created a PR: https://github.com/mpicard/mpicard.github.io/pull/2

**Comment by mpicard** [comment]
Thanks for reading and thanks for letting me know about the link! I’ll merge that ASAP. I’m almost done the next post so check back tomorrow or Monday!
