### ISSUE TITLE
Add resources for AR development

### ISSUE THREAD

**Issue by dhruvmalik007** [danistefanovic/build-your-own-x#97]
### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized
* [ ] Augmented Reality

**Comment by danistefanovic** [comment]
Great idea. Can you suggest some tutorials?

**Comment by dhruvmalik007** [comment]
Tutorial on developing apps on hololens:- 
https://docs.microsoft.com/en-us/windows/mixed-reality/academy

Android AR Core:-
https://developers.google.com/ar/develop/java/quickstart

**Comment by danistefanovic** [comment]
Added. Thank you!
