### ISSUE TITLE
Regular Expressions using Derivatives

### ISSUE THREAD

**Issue by mtn** [danistefanovic/build-your-own-x#99]
### Main programming language

Javascript

### Tutorial title

How to implement regular expressions in functional javascript using derivatives

### Tutorial URL

http://dpk.io/dregs/toydregs

### Category
* [ ] 3D Renderer
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [x] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

It's super good -- walking through a realistic regex implementation, though without talking about parsing. 🎈

**Comment by danistefanovic** [comment]
Great, thanks a lot!
